Select distinct ASD.PROVIDER_ID, ASD.PRACTICE_ID, PP.FIRST_NAME, PP.LAST_NAME, TITLE, NPI, MAIN_SPECIALTY, PRACTICE_NAME, 'IntegratedButNoAvailability' as bucket, SSD.SYNC_TYPE 
From "CISTERN"."PROVIDER_ANALYTICS"."PROVIDER_LOCATION_AVAILABILITY_SUMMARY_DAY" as ASD
join "CISTERN"."PROVIDER"."LOCATION"  as PL on PL.PRACTICE_ID = ASD.PRACTICE_ID
join "CISTERN"."PROVIDER"."PROVIDER" as PP on PP.PROVIDER_ID = ASD.PROVIDER_ID
join "CISTERN"."PROVIDER_ANALYTICS"."PROVIDER_LOCATION_SYNC_SUMMARY_DAY_VW" as SSD on SSD.PROVIDER_ID = ASD.PROVIDER_ID
where ASD.SNAPSHOT_DATE_EASTERN > '2023-12-01'
and ASD.HAS_AVAILABILITY = 'False'
and SOFTWARE ilike '%raintree%'
and SYNC_TYPE <> 'Manual'


and (ASD.PROVIDER_ID not in(''))  // put in provider IDs of the providers who’ve had appointments
